name: $(BuildDefinitionName)_$(date:yyyyMMdd)$(rev:.r)

trigger: 
- master

pool:
  name: 'OptumDotNet'

steps:
  - task: CopyFiles@2
    inputs:
       SourceFolder: '$(agent.builddirectory)'
       Contents: '**'
       TargetFolder: '$(build.artifactstagingdirectory)'
       
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'terraformStoragedrop'
      publishLocation: 'Container'